/***
 * Excerpted from "Real-World Event Sourcing",
 * published by The Pragmatic Bookshelf.
 * Copyrights apply to this code. It may not be used to create training material,
 * courses, books, articles, and the like. Contact us if you are in doubt.
 * We make no guarantees that this code is fit for any purpose.
 * Visit https://pragprog.com/titles/khpes for more book information.
***/
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: buildingspawned.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from buildingspawned.proto</summary>
public static partial class BuildingspawnedReflection {

  #region Descriptor
  /// <summary>File descriptor for buildingspawned.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BuildingspawnedReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVidWlsZGluZ3NwYXduZWQucHJvdG8iHQoFUG9pbnQSCQoBeBgBIAEoDRIJ",
          "CgF5GAIgASgNIqcBCg9CdWlsZGluZ1NwYXduZWQSDwoHc2l0ZV9pZBgBIAEo",
          "CRIPCgdnYW1lX2lkGAIgASgJEhwKCXNpdGVfdHlwZRgDIAEoDjIJLlNpdGVU",
          "eXBlEhgKCGxvY2F0aW9uGAQgASgLMgYuUG9pbnQSEQoJcGxheWVyX2lkGAUg",
          "ASgJEg0KBXRpY2tzGAYgASgEEhgKEGNvbXBsZXRpb25fdGlja3MYByABKA0q",
          "UgoIU2l0ZVR5cGUSBgoCSFEQABIUChBPWFlHRU5fR0VORVJBVE9SEAESEwoP",
          "V0FURVJfR0VORVJBVE9SEAISEwoPUE9XRVJfR0VORVJBVE9SEANiBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::SiteType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Point), global::Point.Parser, new[]{ "X", "Y" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BuildingSpawned), global::BuildingSpawned.Parser, new[]{ "SiteId", "GameId", "SiteType", "Location", "PlayerId", "Ticks", "CompletionTicks" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum SiteType {
  [pbr::OriginalName("HQ")] Hq = 0,
  [pbr::OriginalName("OXYGEN_GENERATOR")] OxygenGenerator = 1,
  [pbr::OriginalName("WATER_GENERATOR")] WaterGenerator = 2,
  [pbr::OriginalName("POWER_GENERATOR")] PowerGenerator = 3,
}

#endregion

#region Messages
public sealed partial class Point : pb::IMessage<Point>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Point> _parser = new pb::MessageParser<Point>(() => new Point());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Point> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BuildingspawnedReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Point() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Point(Point other) : this() {
    x_ = other.x_;
    y_ = other.y_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Point Clone() {
    return new Point(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private uint x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "y" field.</summary>
  public const int YFieldNumber = 2;
  private uint y_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Y {
    get { return y_; }
    set {
      y_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Point);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Point other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (X != other.X) return false;
    if (Y != other.Y) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0) hash ^= X.GetHashCode();
    if (Y != 0) hash ^= Y.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (X != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(X);
    }
    if (Y != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (X != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(X);
    }
    if (Y != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Y);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (X != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(X);
    }
    if (Y != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Y);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Point other) {
    if (other == null) {
      return;
    }
    if (other.X != 0) {
      X = other.X;
    }
    if (other.Y != 0) {
      Y = other.Y;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          X = input.ReadUInt32();
          break;
        }
        case 16: {
          Y = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          X = input.ReadUInt32();
          break;
        }
        case 16: {
          Y = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class BuildingSpawned : pb::IMessage<BuildingSpawned>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BuildingSpawned> _parser = new pb::MessageParser<BuildingSpawned>(() => new BuildingSpawned());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BuildingSpawned> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BuildingspawnedReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuildingSpawned() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuildingSpawned(BuildingSpawned other) : this() {
    siteId_ = other.siteId_;
    gameId_ = other.gameId_;
    siteType_ = other.siteType_;
    location_ = other.location_ != null ? other.location_.Clone() : null;
    playerId_ = other.playerId_;
    ticks_ = other.ticks_;
    completionTicks_ = other.completionTicks_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BuildingSpawned Clone() {
    return new BuildingSpawned(this);
  }

  /// <summary>Field number for the "site_id" field.</summary>
  public const int SiteIdFieldNumber = 1;
  private string siteId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string SiteId {
    get { return siteId_; }
    set {
      siteId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "game_id" field.</summary>
  public const int GameIdFieldNumber = 2;
  private string gameId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string GameId {
    get { return gameId_; }
    set {
      gameId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "site_type" field.</summary>
  public const int SiteTypeFieldNumber = 3;
  private global::SiteType siteType_ = global::SiteType.Hq;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::SiteType SiteType {
    get { return siteType_; }
    set {
      siteType_ = value;
    }
  }

  /// <summary>Field number for the "location" field.</summary>
  public const int LocationFieldNumber = 4;
  private global::Point location_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Point Location {
    get { return location_; }
    set {
      location_ = value;
    }
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 5;
  private string playerId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PlayerId {
    get { return playerId_; }
    set {
      playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "ticks" field.</summary>
  public const int TicksFieldNumber = 6;
  private ulong ticks_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong Ticks {
    get { return ticks_; }
    set {
      ticks_ = value;
    }
  }

  /// <summary>Field number for the "completion_ticks" field.</summary>
  public const int CompletionTicksFieldNumber = 7;
  private uint completionTicks_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CompletionTicks {
    get { return completionTicks_; }
    set {
      completionTicks_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BuildingSpawned);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BuildingSpawned other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SiteId != other.SiteId) return false;
    if (GameId != other.GameId) return false;
    if (SiteType != other.SiteType) return false;
    if (!object.Equals(Location, other.Location)) return false;
    if (PlayerId != other.PlayerId) return false;
    if (Ticks != other.Ticks) return false;
    if (CompletionTicks != other.CompletionTicks) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SiteId.Length != 0) hash ^= SiteId.GetHashCode();
    if (GameId.Length != 0) hash ^= GameId.GetHashCode();
    if (SiteType != global::SiteType.Hq) hash ^= SiteType.GetHashCode();
    if (location_ != null) hash ^= Location.GetHashCode();
    if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
    if (Ticks != 0UL) hash ^= Ticks.GetHashCode();
    if (CompletionTicks != 0) hash ^= CompletionTicks.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SiteId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SiteId);
    }
    if (GameId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GameId);
    }
    if (SiteType != global::SiteType.Hq) {
      output.WriteRawTag(24);
      output.WriteEnum((int) SiteType);
    }
    if (location_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Location);
    }
    if (PlayerId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(PlayerId);
    }
    if (Ticks != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(Ticks);
    }
    if (CompletionTicks != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(CompletionTicks);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SiteId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(SiteId);
    }
    if (GameId.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(GameId);
    }
    if (SiteType != global::SiteType.Hq) {
      output.WriteRawTag(24);
      output.WriteEnum((int) SiteType);
    }
    if (location_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(Location);
    }
    if (PlayerId.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(PlayerId);
    }
    if (Ticks != 0UL) {
      output.WriteRawTag(48);
      output.WriteUInt64(Ticks);
    }
    if (CompletionTicks != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(CompletionTicks);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SiteId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(SiteId);
    }
    if (GameId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(GameId);
    }
    if (SiteType != global::SiteType.Hq) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SiteType);
    }
    if (location_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Location);
    }
    if (PlayerId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
    }
    if (Ticks != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Ticks);
    }
    if (CompletionTicks != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CompletionTicks);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BuildingSpawned other) {
    if (other == null) {
      return;
    }
    if (other.SiteId.Length != 0) {
      SiteId = other.SiteId;
    }
    if (other.GameId.Length != 0) {
      GameId = other.GameId;
    }
    if (other.SiteType != global::SiteType.Hq) {
      SiteType = other.SiteType;
    }
    if (other.location_ != null) {
      if (location_ == null) {
        Location = new global::Point();
      }
      Location.MergeFrom(other.Location);
    }
    if (other.PlayerId.Length != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.Ticks != 0UL) {
      Ticks = other.Ticks;
    }
    if (other.CompletionTicks != 0) {
      CompletionTicks = other.CompletionTicks;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          SiteId = input.ReadString();
          break;
        }
        case 18: {
          GameId = input.ReadString();
          break;
        }
        case 24: {
          SiteType = (global::SiteType) input.ReadEnum();
          break;
        }
        case 34: {
          if (location_ == null) {
            Location = new global::Point();
          }
          input.ReadMessage(Location);
          break;
        }
        case 42: {
          PlayerId = input.ReadString();
          break;
        }
        case 48: {
          Ticks = input.ReadUInt64();
          break;
        }
        case 56: {
          CompletionTicks = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          SiteId = input.ReadString();
          break;
        }
        case 18: {
          GameId = input.ReadString();
          break;
        }
        case 24: {
          SiteType = (global::SiteType) input.ReadEnum();
          break;
        }
        case 34: {
          if (location_ == null) {
            Location = new global::Point();
          }
          input.ReadMessage(Location);
          break;
        }
        case 42: {
          PlayerId = input.ReadString();
          break;
        }
        case 48: {
          Ticks = input.ReadUInt64();
          break;
        }
        case 56: {
          CompletionTicks = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
